### ISSUE TITLE
Cookies not present on request originating from SSR request

### ISSUE THREAD

**Issue by canastro** [bevm0/trpc-svelte-toolbox#3]
I'm in a pickle with the client setup. I have the following two issues:

1. I would like to use relative URLs (/api/trpc) but this fails when a request is originated from a component in SSR... It says `Cannot use relative URL (/api/trpc/getCandidatesQuery?batch=1&input=%7B%7D) with global fetch — use event.fetch`  but I have no way to inject event.fetch into this client.

2. If I obey to the warning and just use a full URL(not exactly what I wanted) I've noticed that my cookie is not sent along with the request and therefore my request fails with due not this being a protected procedure only for authenticated users. 

Have you faced similar challenges? How do you deal with this? 
Also, how do you setup the client so that you don't have to hardcode a full URL?

**Comment by canastro** [comment]
Is the only solution ensure that no request is made from the server-side at the component level? 

Something like:

```ts
	const candidates = trpc.getCandidatesQuery.createQuery(undefined, {
		refetchOnWindowFocus: false,
		enabled: browser
	});
```

This seems to be a bit brittle, and I dont see this being done in any of the examples, was this never a problem for your apps?

**Comment by ap0nia** [comment]
I definitely did encounter these sorts of issues. Cookies only work during SSR when using SvelteKit's `event.fetch` because they do additional, framework-specific processing that Node's global polyfill doesn't.

Per this note, the strategy I've settled with for now is to create two tRPC clients that share context within components, but originate from distinct locations. https://trpc-svelte-toolbox.vercel.app/sveltekit/setup#6-setup-layoutsvelte

It's correct that the client created for components, e.g. in `$lib/trpc/client` should have queries only enabled in the browser, since it shouldn't be used server side. A specialized version of the tRPC client should be initialized in `src/routes/+layout.ts` that correctly uses SvelteKit's `event.fetch` to make requests.

```ts
import { httpBatchLink } from '@trpc/client';
import { createTRPCSvelte } from '@bevm0/trpc-svelte';
import { QueryClient } from '@tanstack/svelte-query'
import type { AppRouter } from '$lib/server/trpc/routers';

export const load: LayoutLoad = async (event) => {
  const queryClient = new QueryClient()

  const trpc = createTRPCSvelte<AppRouter>({
    links: [
      httpBatchLink({ 
        url: 'http://localhost:5173/api/trpc',
        fetch: event.fetch  // pass SvelteKit's custom fetch function
      }),
    ],
  }, { svelteQueryContext: queryClient });

  return { trpc }
}
```

In load functions, e.g. `src/routes/+page.ts`, you should use this special trpc instead of the client one, like so: https://trpc-svelte-toolbox.vercel.app/sveltekit/setup#8-prefetch-an-api-request-from-a-load-function

```ts
import type { PageLoad } from './$types'

export const load: PageLoad = async ({ parent }) => {
  // use the initialized tRPC client from the parent +layout.ts
  const { trpc } = await parent()

  // in components, if you didn't specify the `svelteQueryContext` in `src/lib/trpc.ts` -- i.e. like the guide,
  // you should use `getContext()` because `context` wasn't able to be computed.
  return {
    greeting: trpc.context.hello.fetch({ text: 'client' });
  }
}
```

## Under the Hood
The tRPC client that's initialized for components, e.g. `$lib/trpc/client`, is not intended to be used server side because the server will initialize a single instance of its own on startup, whereas clients will re-create one when somebody visits the website for the first time. The instance that's created on the server should **not** be used to make requests because it could leak data between clients, since its a single, shared instance for all requests.

The tRPC client for components also doesn't have its own query client for making and caching requests, which is specified with `svelteQueryContext` in the `src/routes/+layout.ts` version. Once the page loads, the client that was initialized in the layout load function with invoke `setContext` to share this query client with the client side client. This prevents data leakage between users because a new query client is created in every user's load function, but also allows developers to import from a more convenient alias.

## Further Discussion
Does it seem strange that there are multiple clients? Because the client created in the root layout is part of shared page data, the alternative would look like this:
```svelte
<script lang="ts">
  import { page } from '$app/stores'
  const { trpc } = $page.data

  // vs
  import { trpc } from '$lib/trpc/client'
</script>
```
I just didn't really like having to always do 2 lines of code, and it deviates from more common examples, i.e. usage in NextJS. However, it seems necessary because NextJS's adapter uses a completely distinct SSR strat with [`react-ssr-prepass`](https://www.npmjs.com/package/react-ssr-prepass) to find all promises originating from tRPC queries and prefetch them. The most SvelteKit-idiomatic equivalent seems to be using load functions to prefetch. Any thoughts? I just came up with these things on my own, so I'm not sure how others feel.

**Comment by canastro** [comment]
Looking from a consumer of this API standpoint (and not really on the feasibility of things) it feels weird to:
1. have two clients (specifically because one of the clients can be executed from two different contexts and therefore has two different behaviours *)
2. have to define all component-queries to just run on client-side. It feels error-prone and to defeat the purpose of having an SSR framework. (I usually have the initial queries on the load function, but this particular case I had a query that was very specific to a deeply nested component)

My application is a SASS product that has the routes specific to a organization under `/:handle/something`, I need to pass this handle via a specific header.

My "load-function-client":
```ts
const trpc = createTRPCSvelte<AppRouter>(
  {
    links: [
      httpBatchLink({
        url: '/api/rpc',
        fetch: event.fetch,
        headers: { 'x-organization-handle': event.params.handle }
      })
    ]
  },
  { svelteQueryContext: queryClient }
);
```

My 'component-client':
```ts
export const trpc = createTRPCSvelte<AppRouter>({
  links: [
    httpBatchLink({
      url: '/api/rpc',
      // TODO: we need to find a better way to get the organization handle, right now we
      //   only have procedures under /:handle, so we can just split the pathname
      headers: () => {
        if (typeof window === 'undefined') {
          throw new Error('this client should not be used in server-side');
        }

        return { 'x-organization-handle': window.location.pathname.split('/')[1] };
      }
    })
  ]
});
``` 

As you can see in the component-side-client I have some weird guard for when it is executed from the server-side. 


PS: Im sorry if I'm not being very helpful, I've started working with TRPC and tanstack-query this week, so its still all too new to me. I can only provide you the view of a newcomer.

**Comment by ap0nia** [comment]
## tRPC client strategy
It's a WIP and I greatly appreciate the feedback! I'll continue working refining this; I took a break from it since nobody had any opinions on it lol.

## Setting Headers based on `event.params`
Internally, the SvelteKit adapter uses tRPC's fetch adapter, documented here: https://trpc.io/docs/server/adapters/fetch.
It's possible to edit the event before it reaches the tRPC handlers. I've left an example here https://github.com/ap0nia/trpc-svelte-toolbox/blob/main/examples/kitchen-sink/src/routes/api/trpc/%5B...path%5D/%2Bserver.ts

Is the header significant to other services in the backend, or only tRPC? `createContext` is usually a good place to put any additional metadata if the latter is the case. But hopefully these examples are helpful! 

```ts
import { appRouter } from '$lib/server/trpc/routes'
import type { AppRouter } from '$lib/server/trpc/routes'
import { createTRPCRequestHandler } from '@bevm0/trpc-sveltekit'
import type { RouteParams, RouteId } from './$types'
import { createContext } from '$lib/server/trpc/context'
import type { RequestHandler } from './$types'

const trpcRequestHandler = createTRPCRequestHandler<AppRouter, RouteParams, RouteId>({
    router: appRouter,
    createContext
  })

const requestHandler: RequestHandler = event => {
  event.request.headers.set('x-organization-handle', event.params.path)
  return trpcRequestHandler(event)
}

export const GET = requestHandler
export const POST = requestHandler
```

**Comment by canastro** [comment]
I've been using houdini in the past, and houdini's client setup was quite nice, it supported two things that were very helpful.

This is how the client is setup:
```ts
export default new HoudiniClient({
	url: '/api/graphql',
	fetchParams: ({ metadata, session }) => {
		const organizationHandle = metadata?.organizationHandle ?? session?.organizationHandle;

		const headers: Record<string, string> = organizationHandle
			? { [organizationHandleHeader]: organizationHandle }
			: {};

		return {
			headers
		};
	}
});
```

As you can see houdini's client receives a "metadata" and a "session".

This session was something to which you could set values from a sveltekit hook for example, and this metadata could be passed directly from any query. This allowed me to:

1. in a case where the user is in a page that its still not in the selected organization (eg. still in the onboarding process) to do:
```ts
const result = await inviteMembers.mutate(
	{ input: { invites: values.invites.filter(isInvite) } },
	{ metadata: { organizationHandle } }
);
```

2. whenever the user selects the organization, we had a sveltekit hook that just sets the handle:
```ts
export const handleOrganizationHandle: Handle = async ({ event, resolve }) => {
	const { handle } = event.params;

	if (!handle) {
		return resolve(event);
	}

	setSession(event, { organizationHandle: handle });

	return resolve(event);
};
```

Right now, with trpc-svelte-query, I've been using the URL to get the handle and set the headers, but not sure how I can address the scenario described in the first point.

**Comment by ap0nia** [comment]
I see. This is tough because this should be a limitation of tRPC's API, not a direct consequence of svelte-query. Houdini's API allows you to pass in a lot of useful data ***prior*** to the fetch request occurring. Per tRPC's docs, the following options offer the ability to dynamically adjust the fetch request (albeit in a different manner)

A function is invoked per request to generate headers: https://trpc.io/docs/client/headers
You could read from a custom client-side store or the page data store to set the headers.

You can mutate the fetch call directly: https://trpc.io/docs/client/links/httpBatchLink#httpbatchlink-options
^This is how SvelteKit's `event.fetch` is passed used for the tRPC client in load functions. 

The ability to pass useful metadata from a function (mutation) invocation and use that when generating these properties is not inherently part of tRPC or svelte-query's API at all.

Personally, I'd isolate the organization switching to a dedicated tRPC endpoint, or process it within tRPC context or middleware. The tRPC server has access to both the fetch adapter headers and SvelteKit event (with my SvelteKit adapter, which has a different API from NextJS)

https://trpc.io/docs/server/authorization#create-context-from-request-headers
https://trpc.io/docs/server/middlewares

tRPC has its own lifecycles, and it's difficult to interweave them with SvelteKit's handlers. tRPC's server does still receive the original event object, and can read/mutate it as necessary. i.e. you could process the event in `createContext` or in a custom middleware that checks the organization and sets it accordingly.

A caveat when working with the event within the tRPC server is that the final response is a custom `new Response`, so you'd have to call `ctx.opts.resHeaders.set(...)` to get the custom response to have the correct headers.

**Comment by canastro** [comment]
Thank you very much, this has indeed been super useful and gave me alternatives to explore!

**Comment by canastro** [comment]
We can close this issue, I was able to address most of my issues with one of your suggestions. I'll share here the approach just if anyone ever lands on this issue and might be interested.

For some reason I got "blocked" on the fact that the "component" client could be called from the server-side and never thought on blocking non-browser usages and just use a store to pass in information to the headers.

So now, this is my client:

```ts
export const trpc = createTRPCSvelte<AppRouter>({
	transformer: superjson,
	links: [
		httpBatchLink({
			url: '/api/rpc',
			headers: () => {
				if (!browser) {
					throw new Error('Cannot use this client on the server side');
				}

				const { handle } = get(trpcClientSession);

				return { 'x-organization-handle': handle };
			}
		})
	]
});
```

And this is in my base +layout.svelte:

```ts
$: trpcClientSession.setHandle($page.params.handle);
```

And this allows me to manually set the handle even if its not part of the params (just like my "onboarding" case).

**Comment by ap0nia** [comment]
Thank you for sharing! 🙌
